# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (5)
# #########################################################################

class FinancialAnswer(BaseModel):
    answerable: typing.Optional[bool] = None
    answer: typing.Optional[str] = None

class NumericEvidence(BaseModel):
    source_file: typing.Optional[str] = None
    sql: typing.Optional[str] = None
    rows_csv: typing.Optional[str] = None

class SemanticEvidence(BaseModel):
    source_file: typing.Optional[str] = None
    title: typing.Optional[str] = None
    author: typing.Optional[str] = None
    participants: typing.Optional[str] = None
    date: typing.Optional[str] = None
    content: typing.Optional[str] = None

class TableInfo(BaseModel):
    table_index: typing.Optional[int] = None
    filename: typing.Optional[str] = None
    ingested_schema: typing.Optional[str] = None
    columns: typing.Optional[str] = None
    sample_rows: typing.Optional[str] = None

class TableSql(BaseModel):
    table_index: typing.Optional[int] = None
    relevant: typing.Optional[bool] = None
    sql: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
