# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (5)
# #########################################################################

class FinancialAnswer(BaseModel):
    answerable: bool
    answer: str

class NumericEvidence(BaseModel):
    source_file: str
    sql: str
    rows_csv: str

class SemanticEvidence(BaseModel):
    source_file: str
    title: str
    author: str
    participants: str
    date: str
    content: str

class TableInfo(BaseModel):
    table_index: int
    filename: str
    ingested_schema: str
    columns: str
    sample_rows: str

class TableSql(BaseModel):
    table_index: int
    relevant: bool
    sql: str

# #########################################################################
# Generated type aliases (0)
# #########################################################################
