# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.FinancialAnswer": types.FinancialAnswer,
    "stream_types.FinancialAnswer": stream_types.FinancialAnswer,

    "types.NumericEvidence": types.NumericEvidence,
    "stream_types.NumericEvidence": stream_types.NumericEvidence,

    "types.SemanticEvidence": types.SemanticEvidence,
    "stream_types.SemanticEvidence": stream_types.SemanticEvidence,

    "types.TableInfo": types.TableInfo,
    "stream_types.TableInfo": stream_types.TableInfo,

    "types.TableSql": types.TableSql,
    "stream_types.TableSql": stream_types.TableSql,


}